defaults: &defaults
  icons:
    EAT: 'fas fa-utensils'
    BUS: 'fas fa-bus'
    Bicycle: 'fas fa-bicycle'
    Taxi: 'fas fa-taxi'
    Truck: 'fas fa-truck'
    Plane: 'fas fa-plane'
    Cloud: 'fas fa-cloud'
    Ticket: 'fas fa-ticket-alt'
    Mask: 'fas fa-mask'
    Fish: 'fas fa-fish'
    Utensils: 'fas fa-utensils'
    Tshirt: 'fas fa-tshirt'
    Shopping: 'fas fa-shopping-cart'
    Film: 'fas fa-film'
    Beer: 'fas fa-beer'
    Coffee: 'fas fa-coffee'
    Cocktail: 'fas fa-cocktail'
    Dumbbell: 'fas fa-dumbbell'
    Bed: 'fas fa-bed'
    Book: 'fas fa-book'
    Bullhorn: 'fas fa-bullhorn'
    'Charging-station': 'fas fa-charging-station'
    Dharmachakra: 'fas fa-dharmachakra'
    'Map-marker': 'fas fa-map-marker-alt'
    Gamepad: 'fas fa-gamepad'
    Home: 'fas fa-home'
    Capsules: 'fas fa-capsules'
    "Concierge-bell": 'fas fa-concierge-bell'
    Music: 'fab fa-itunes-note'
    Astronaut: 'fas fa-user-astronaut'

development:
  <<: *defaults
  redis_connection:
    host: "127.0.0.1"
    port: 6379
    db: 15


test:
  <<: *defaults
  redis_connection:
    host: "127.0.0.1"
    port: 6379
    db: 15

production:
  <<: *defaults
  redis_connection:
    host: "127.0.0.1"
    port: 6379
    db: 15
