class Store::Introduction < ApplicationRecord
  # extends ...................................................................
  # includes ..................................................................
  # security (i.e. attr_accessible) ...........................................
  # relationships .............................................................
  belongs_to :store
  # validations ...............................................................
  validates_presence_of :attachment
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  enum menu_type: [:information, :service]

  mount_uploader :attachment, ImageUploader

  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
