class Area < ApplicationRecord
  # extends ...................................................................
  # includes ..................................................................
  # security (i.e. attr_accessible) ...........................................
  # relationships .............................................................
  belongs_to :city
  # validations ...............................................................
  # callbacks .................................................................
  # scopes ....................................................................
  default_scope { order(position: :asc) }
  # additional config .........................................................
  # class methods .............................................................
  def self.formated_options
    self.options include_blank: false, text_column: :full_name
  end
  # public instance methods ...................................................
  def full_name
    "#{name}(#{zip_code})"
  end
  # protected instance methods ................................................
  # private instance methods ..................................................
end
