class Channel < ApplicationRecord
  # extends ...................................................................
  # includes ..................................................................
  # security (i.e. attr_accessible) ...........................................
  # relationships .............................................................
  has_many :programs
  # validations ...............................................................
  validates_presence_of :name
  # callbacks .................................................................
  # scopes ....................................................................
  scope :active, -> { where(is_active: true) }
  # additional config .........................................................
  # class methods .............................................................
  # public instance methods ...................................................
  def formated_api
    {
      id: self.id,
      name: self.name,
      icon: self.icon,
    }
  end
  # protected instance methods ................................................
  # private instance methods ..................................................
end
