class Headquarter < ApplicationRecord
  # extends ...................................................................
  # includes ..................................................................
  # security (i.e. attr_accessible) ...........................................
  # relationships .............................................................
  has_many :stores
  # validations ...............................................................
  validates_presence_of :name
  validates :commission, numericality: { greater_than_or_equal_to: 0, less_than_or_equal_to: 100 }
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  #
  DEFAULT_VALUES = { commission: 15 }
  # class methods .............................................................
  # public instance methods ...................................................
  # protected instance methods ................................................
  # private instance methods ..................................................
end
