class TmpFile < ApplicationRecord
  # extends ...................................................................
  # includes ..................................................................
  # security (i.e. attr_accessible) ...........................................
  # relationships .............................................................
  # validations ...............................................................
  validates_presence_of :file
  # callbacks .................................................................
  # scopes ....................................................................
  # additional config .........................................................
  mount_uploader :file, TmpFileUploader
  # class methods .............................................................
  # public instance methods ...................................................
  def url
    self.file.url
  end

  def info
    {
      url: self.url,
      size: self.size,
      md5: self.md5
    }
  end

  # protected instance methods ................................................
  # private instance methods ..................................................
end
